import{a as h,S as L,i as a}from"./assets/vendor-BIrBgRnv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))p(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&p(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function p(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();h.defaults.baseURL="https://pixabay.com/api/";const v="54466384-09b1ba24b9e280fec4b671a93",f=async(s,t)=>{try{return(await h.get("",{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(o){console.log("Помилка запиту:",o)}},c=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),S=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),m=s=>{if(!c)return;const t=s.map(o=>`
      <li class="photo-card">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="photo-info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>
    `).join("");c.insertAdjacentHTML("beforeend",t),S.refresh()},q=()=>{c&&(c.innerHTML="")},y=()=>{l&&l.classList.remove("hidden")},g=()=>{l&&l.classList.add("hidden")},P=()=>{d&&d.classList.remove("hidden")},b=()=>{d&&d.classList.add("hidden")},E=document.querySelector(".inpt"),R=document.querySelector(".form"),M=document.querySelector(".load-more");let i="",n=1;const w=15;R.addEventListener("submit",async s=>{if(s.preventDefault(),i=E.value.trim(),!i){a.show({position:"topRight",color:"red",title:"Error",message:"Please enter a search query"});return}n=1,q(),b(),y();try{const t=await f(i,n);if(!t||t.hits.length===0){a.show({position:"topRight",color:"red",title:"Sorry",message:"there are no images matching your search query. Please try again!",iconUrl:"https://img.icons8.com/?size=100&id=12405&format=png&color=000000"});return}m(t.hits),t.totalHits>w&&P()}catch{a.show({position:"topRight",color:"red",title:"Error",message:"Something went wrong. Please try again later!"})}finally{g()}});M.addEventListener("click",async()=>{n+=1,y();try{const s=await f(i,n);m(s.hits);const t=Math.ceil(s.totalHits/w);n>=t&&(b(),a.show({position:"topRight",color:"blue",title:"Info",message:"We're sorry, but you've reached the end of search results."}));const o=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch{a.show({position:"topRight",color:"red",title:"Error",message:"Something went wrong. Please try again later!"})}finally{g()}});
//# sourceMappingURL=index.js.map
