import{a as f,S as v,i as a}from"./assets/vendor-BIrBgRnv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))p(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&p(h)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function p(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();f.defaults.baseURL="https://pixabay.com/api/";const S="54466384-09b1ba24b9e280fec4b671a93",m=async(s,t)=>{try{return(await f.get("",{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(o){console.log("Помилка запиту:",o)}},l=document.querySelector(".gallery"),c=document.querySelector(".loader"),d=document.querySelector(".load-more"),q=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),g=s=>{if(!l)return;const t=s.map(o=>`
      <li class="photo-card">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="photo-info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>
    `).join("");l.insertAdjacentHTML("beforeend",t),q.refresh()},P=()=>{l&&(l.innerHTML="")},y=()=>{c&&c.classList.remove("hidden")},b=()=>{c&&c.classList.add("hidden")},w=()=>{d&&d.classList.remove("hidden")},u=()=>{d&&d.classList.add("hidden")},R=document.querySelector(".inpt"),E=document.querySelector(".form"),M=document.querySelector(".load-more");let n="",i=1;const L=15;E.addEventListener("submit",async s=>{if(s.preventDefault(),n=R.value.trim(),!n){a.show({position:"topRight",color:"red",title:"Error",message:"Please enter a search query"});return}i=1,P(),u(),y();try{const t=await m(n,i);if(!t||t.hits.length===0){a.show({position:"topRight",color:"red",title:"Sorry",message:"there are no images matching your search query. Please try again!",iconUrl:"https://img.icons8.com/?size=100&id=12405&format=png&color=000000"});return}g(t.hits),t.totalHits<=L?(a.show({position:"topRight",color:"blue",title:"Info",message:"You've reached the end of search results."}),u()):w()}catch{a.show({position:"topRight",color:"red",title:"Error",message:"Something went wrong. Please try again later!"})}finally{b()}});M.addEventListener("click",async()=>{i+=1,y(),u();try{const s=await m(n,i);g(s.hits);const t=Math.ceil(s.totalHits/L);i>=t?(u(),a.show({position:"topRight",color:"blue",title:"Info",message:"You've reached the end of search results."})):w();const o=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch{a.show({position:"topRight",color:"red",title:"Error",message:"Something went wrong. Please try again later!"})}finally{b()}});
//# sourceMappingURL=index.js.map
